services:
  - type: web
    name: smart-waste-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run smart_waste_app.py --server.port $PORT --server.enableCORS false
    plan: free
